In [1]:
import pandas as pd

In [3]:
import glob

# Step 1: Define the folder path where your CSVs are located
folder_path = "/kaggle/input/sales-data"  # Replace with your dataset folder

# Step 2: Get all CSV files in the folder
csv_files = glob.glob(f"{folder_path}/*.csv")

# Step 3: Read and merge all CSV files
df = pd.concat((pd.read_csv(file) for file in csv_files), ignore_index=True)

df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,236670,Wired Headphones,2,11.99,08/31/19 22:21,"359 Spruce St, Seattle, WA 98101"
1,236671,Bose SoundSport Headphones,1,99.99,08/15/19 15:11,"492 Ridge St, Dallas, TX 75001"
2,236672,iPhone,1,700.0,08/06/19 14:40,"149 7th St, Portland, OR 97035"
3,236673,AA Batteries (4-pack),2,3.84,08/29/19 20:59,"631 2nd St, Los Angeles, CA 90001"
4,236674,AA Batteries (4-pack),2,3.84,08/15/19 19:53,"736 14th St, New York City, NY 10001"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186850 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 8.6+ MB

In [5]:
df.isnull().sum()

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

In [6]:
df = df.dropna()

In [7]:
# Remove duplicates while keeping the first occurrence
df = df.drop_duplicates(keep='first')

In [9]:
(df['Product'] == 'Product').sum()

1

In [11]:
df.Product.unique()

array(['Wired Headphones', 'Bose SoundSport Headphones', 'iPhone',
       'AA Batteries (4-pack)', '34in Ultrawide Monitor', '20in Monitor',
       'Macbook Pro Laptop', 'LG Washing Machine', '27in FHD Monitor',
       'Lightning Charging Cable', 'Apple Airpods Headphones',
       'AAA Batteries (4-pack)', 'USB-C Charging Cable',
       '27in 4K Gaming Monitor', 'ThinkPad Laptop', 'Flatscreen TV',
       'Google Phone', 'Vareebadd Phone', 'Product', 'LG Dryer'],
      dtype=object)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185687 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185687 non-null  object
 1   Product           185687 non-null  object
 2   Quantity Ordered  185687 non-null  object
 3   Price Each        185687 non-null  object
 4   Order Date        185687 non-null  object
 5   Purchase Address  185687 non-null  object
dtypes: object(6)
memory usage: 9.9+ MB